### ISSUE TITLE
More resources on enshrined-in-consensus

### ISSUE THREAD

**Issue by hswick** [Drops-of-Diamond/Diamond-drops#19]
Hi! Wanted to say great work so far. 

This isn't probably the best place to ask this, but...

I noticed you used the term enshrined-in-consensus. I was wondering if you could point me to some resources on this and how it relates to data availability. As data availability is a big concern of ours at Truebit. 

Thanks!

**Comment by jamesray1** [comment]
Hi there! The term originated here: https://ethresear.ch/t/sharding-phase-1-spec-retired/1407/18?u=jamesray1. I'm actually reading through a lot of research right now, and interactive verification is a major topic in sharding research right now, so I'm reading through the Truebit white paper! I'll update the wiki as well.

**Comment by jamesray1** [comment]
Phase 1 is only enshrining-in-consensus data availability. There is no execution or dapps. The EVM state transition function will be in phase 2, and executors in phase 3. There is no sense of validity because there is no execution. With the latest research [the plan in phase 1](https://ethresear.ch/t/a-minimal-sharding-protocol-that-may-be-worthwhile-as-a-development-target-now/1650) will be that notaries try to download a collation body, vote on it, which emits a log that clients read, and if clients see that >= 2/3 of notaries voted for a chunk (see the glossary [here](https://ethresear.ch/t/sharding-phase-1-spec-retired/1407)) then it will be included in the main chain.

**Comment by jamesray1** [comment]
Also you can reach us on Gitter: https://gitter.im/Drops-of-Diamond/Lobby.

**Comment by jamesray1** [comment]
PS I think I mentioned before but there is a research, Max (maxc on ethresear.ch) who is working on reducing the number of rounds of interactive verification. He would be a good person to collaborate with. I'm partially reading through research and partially reviewing development from my team at the moment. I plan on developing, and reading research as needed to stay up to date as well as for review of research.
